version: '3.8'

services:
  postgres:
    image: postgres:17.6
    container_name: postgres-dev
    environment:
      POSTGRES_DB: idea_spark
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: